config/routes.rb
AccountingSystem::Application.routes.draw do

  resources :accounts do
    resources :payments
  end

  devise_for :users

  root :to => 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :title, :description

  belongs_to :user

  validates_presence_of :title
  validates_length_of :title, :within => 3..50

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :amount, :description, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  #
  has_many :accounts, :dependent => :destroy
end

app/controllers/accounts_controller.rb
# encoding: utf-8
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_account, :only => [:show, :edit, :update, :destroy]

  def index
    @accounts = current_user.accounts.order(:id)
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.build(params[:account])
    if @account.save
      redirect_to new_account_path, :notice => "Счет добавлен"
    else
      render :action => :new
    end
  end

  def edit; end

  def update
    if @account.update_attributes(params[:account])
      redirect_to account_path(@account), :notice => "Счет обновлен"
    else
      render :action => :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path, :notice => "Счет удален"
  end

  private

  def find_account
    @account = current_user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :file => "public/404.html"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def twitterized_type(type)
    case type
      when :alert
        "alert-block"
      when :error
        "alert-error"
      when :notice
        "alert-info"
      when :success
        "alert-success"
      else
        type.to_s
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/accounts/_form.html.haml
= simple_form_for @account do |f|
  = f.error_notification
  .form-inputs
    = f.input :title, :hint => "Например: ВТБ24(рублевый)"
    = f.input :description, :as => :text, :input_html =>{ :style => "width: 510px; height: 150px;" }, :hint => " Например: БИК: 7654321, ИНН: 9876543212345  "
    = f.hint 'Здесь вы можете заполнить номер счета, информацию о банке, электронной валюте и т.п.'

  .form-actions
    = f.button :submit

app/views/accounts/edit.html.haml
%h1 Редактировать счет
= render "form"

app/views/accounts/index.html.haml
%h1 Список счетов


%table.table
  %tr
    %th #
    %th Название
    %th Остаток
    %th Описание
    %th Управление
  - @accounts.each_with_index do |account, idx|
    %tr
      %td= idx+1
      %td= link_to account.title, account_path(account)
      %td= account.summa
      %td= truncate account.description
      %td
        .dropdown
          %button.btn.dropdown-toggle.btn-mini{ "data-toggle"=>"dropdown" }
            Действие
            %span.caret
          %ul.dropdown-menu
            %li= link_to "Перевод на счет"
            %li= link_to "Перевод cо счета"
            %li= link_to "Выписка"
            %li.divider
            %li= link_to "Редактировать", edit_account_path(account)

app/views/accounts/new.html.haml
%h1 Добавить счет
= render "form"

app/views/accounts/show.html.haml
.row
  %span.span5
    %h3 Счет #{@account.title} [#{ link_to number_to_currency( @account.summa ), "#"}]
  %span.span4
    .pull-right
      .dropdown
        %button.btn.dropdown-toggle{ "data-toggle"=>"dropdown" }
          Управление
          %span.caret
        %ul.dropdown-menu
          %li= link_to "Перевод на счет"
          %li= link_to "Перевод cо счета"
          %li= link_to "Выписка"
          %li.divider
          %li= link_to "Редактировать", edit_account_path(@account)

%br
.initialism
  %blockquote= simple_format(@account.description)


#delete_button
  = link_to "Удалить", account_path(@account), :method => :delete, :confirm => "Подтверждаете?", :class=>"btn btn-danger btn-mini"

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "AccountingSystem"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"

    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body

    .navbar-invers.navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Accounting System
          .container.nav-collapse
            %ul.nav.pull-right
              - if current_user
                %li= link_to "<i class=\"icon-edit\"></i>#{ current_user.email }".html_safe, edit_user_registration_path(:current)
                %li= link_to "Выход", destroy_user_session_path, :method => :delete

              - else
                %li= link_to "Регистрация", new_user_registration_path
                %li
                  = link_to( "<i class=\"icon-user\"></i>Войти".html_safe, new_user_session_path )

    .container

      .content
        .row
          .span9
            =render :partial => "shared/flashes", :locals => {:flash => flash}
            = yield
          - if signed_in?
            .span3
              .well.sidebar-nav
                %ul.nav.nav-list
                  %li.sidebar-link.head_link
                    .add_btn.pull-right.sidebar-link_actions
                      = link_to new_account_path, :class => 'btn btn-mini' do
                        %i.icon-plus-sign
                        = "Добавить"
                    %h3= link_to "Счета", accounts_path
                  - current_user.accounts.each do |account|
                    %li= link_to account.title, account_path(account)

      %footer.footer
        %p &copy; #{ link_to "Devmen 2012", "http://devmen.com"}

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

    :javascript
      $(".alert").alert();
      $('.dropdown-toggle').dropdown();

app/views/payments/delete.html.haml
%h1 Payments#delete
%p Find me in app/views/payments/delete.html.haml

app/views/payments/edit.html.haml
%h1 Payments#edit
%p Find me in app/views/payments/edit.html.haml

app/views/payments/index.html.haml
%h1 Payments#index
%p Find me in app/views/payments/index.html.haml

app/views/payments/new.html.haml
%h1 Payments#new
%p Find me in app/views/payments/new.html.haml

app/views/shared/_flashes.html.haml
- flash.each do |type, message|
  .alert.fide.in{:class=>twitterized_type(type), "data-dismiss"=>"alert"}
    %button.alert{ :type=>"button", :class=>"close"  } ×
    = message